#订单模块配置
apiVersion: v1
kind: ConfigMap
metadata:
  name: order-config
  namespace: istio-demo
data:
  application-test.yml: |
    server:
      port: 8000
    spring:
      datasource:
        driver-class-name: com.mysql.jdbc.Driver
        url: jdbc:mysql://120.55.78.23:3306/order?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=GMT%2B8
        username: root
        password: 365tskj.dev123456
---
#商品模块配置
apiVersion: v1
kind: ConfigMap
metadata:
  name: goods-config
  namespace: istio-demo
data:
  application-test.yml: |
    server:
      port: 8001
    spring:
      r2dbc:
        url: r2dbc:mysql://120.55.78.23:3306/goods?useSSL=false
        username: root
        password: 365tskj.dev123456
---
#库存模块配置
apiVersion: v1
kind: ConfigMap
metadata:
  name: stock-config
  namespace: istio-demo
data:
  application-test.yml: |
    server:
      port: 8002
    spring:
      datasource:
        driver-class-name: com.mysql.jdbc.Driver
        url: jdbc:mysql://120.55.78.23:3306/order?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=GMT%2B8
        username: root
        password: 365tskj.dev123456