apiVersion: v1
kind: Service
metadata:
  name: order
  namespace: istio-demo
  labels:
    app: order
    service: order
    admin: enabled
spec:
  ports:
    - port: 8000
      name: http
  selector:
    app: order
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: order-account
  namespace: istio-demo
  labels:
    account: order
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: order
  namespace: istio-demo
  labels:
    app: order
    version: v1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: order
      version: v1
  template:
    metadata:
      labels:
        app: order
        version: v1
    spec:
      serviceAccountName: order-account
      volumes:
        - name: order-cm-volume
          configMap:
            name: order-cm
      containers:
        - name: order
          image: registry.cn-hangzhou.aliyuncs.com/365tskj-backend-old/order-api:latest
          imagePullPolicy: Always
          args: [ " --spring.profiles.active=test,actuator --spring.config.additional-location=/etc/java/*.yml" ]
          ports:
            - containerPort: 8000
              name: http
              protocol: TCP
          securityContext:
            runAsUser: 1000
          volumeMounts:
            - name: order-cm-volume
              mountPath: /etc/java/application-test.yml
              subPath: application-test.yml
          livenessProbe:
            httpGet:
              path: "/actuator/health/liveness"
              port: 8000
            initialDelaySeconds: 10
            periodSeconds: 10
            timeoutSeconds: 3
            successThreshold: 1
            failureThreshold: 5
          readinessProbe:
            httpGet:
              path: "/actuator/health/readiness"
              port: 8000
            initialDelaySeconds: 10
            periodSeconds: 10
            timeoutSeconds: 3
            successThreshold: 1
            failureThreshold: 5

---
apiVersion: v1
kind: Service
metadata:
  name: goods
  namespace: istio-demo
  labels:
    app: goods
    service: goods
    admin: enabled
spec:
  ports:
    - port: 8001
      name: http
  selector:
    app: goods
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: goods-account
  namespace: istio-demo
  labels:
    account: goods
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: goods
  namespace: istio-demo
  labels:
    app: goods
    version: v1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: goods
      version: v1
  template:
    metadata:
      labels:
        app: goods
        version: v1
    spec:
      serviceAccountName: goods-account
      volumes:
        - name: goods-cm-volume
          configMap:
            name: goods-cm
      containers:
        - name: goods
          image: registry.cn-hangzhou.aliyuncs.com/365tskj-backend-old/goods-api:latest
          imagePullPolicy: Always
          args: [ " --spring.profiles.active=test,actuator --spring.config.additional-location=/etc/java/*.yml" ]
          ports:
            - containerPort: 8001
              name: http
              protocol: TCP
          securityContext:
            runAsUser: 1000
          volumeMounts:
            - name: goods-cm-volume
              mountPath: /etc/java/application-test.yml
              subPath: application-test.yml
          livenessProbe:
            httpGet:
              path: "/actuator/health/liveness"
              port: 8001
            initialDelaySeconds: 10
            periodSeconds: 10
            timeoutSeconds: 3
            successThreshold: 1
            failureThreshold: 5
          readinessProbe:
            httpGet:
              path: "/actuator/health/readiness"
              port: 8001
            initialDelaySeconds: 10
            periodSeconds: 10
            timeoutSeconds: 3
            successThreshold: 1
            failureThreshold: 5
---
apiVersion: v1
kind: Service
metadata:
  name: stock
  namespace: istio-demo
  labels:
    app: stock
    service: stock
    admin: enabled
spec:
  ports:
    - port: 8002
      name: http
  selector:
    app: stock
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: stock-account
  namespace: istio-demo
  labels:
    account: stock
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: stock
  namespace: istio-demo
  labels:
    app: stock
    version: v1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: stock
      version: v1
  template:
    metadata:
      labels:
        app: stock
        version: v1
    spec:
      serviceAccountName: stock-account
      volumes:
        - name: stock-cm-volume
          configMap:
            name: stock-cm
      containers:
        - name: stock
          image: registry.cn-hangzhou.aliyuncs.com/365tskj-backend-old/stock-api:latest
          imagePullPolicy: Always
          args: [ " --spring.profiles.active=test,actuator --spring.config.additional-location=/etc/java/*.yml" ]
          ports:
            - containerPort: 8002
              name: http
              protocol: TCP
          securityContext:
            runAsUser: 1000
          volumeMounts:
            - name: stock-cm-volume
              mountPath: /etc/java/application-test.yml
              subPath: application-test.yml
          livenessProbe:
            httpGet:
              path: "/actuator/health/liveness"
              port: 8002
            initialDelaySeconds: 10
            periodSeconds: 10
            timeoutSeconds: 3
            successThreshold: 1
            failureThreshold: 5
          readinessProbe:
            httpGet:
              path: "/actuator/health/readiness"
              port: 8002
            initialDelaySeconds: 10
            periodSeconds: 10
            timeoutSeconds: 3
            successThreshold: 1
            failureThreshold: 5