#订单模块配置
apiVersion: v1
kind: ConfigMap
metadata:
  name: order-cm
  namespace: istio-demo
data:
  application-test.yml: |
    spring:
      datasource:
        driver-class-name: com.mysql.jdbc.Driver
        url: jdbc:mysql://192.168.3.230:3306/order?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=GMT%2B8
        username: order
        password: 365tskj.dev123456
---
#商品模块配置
apiVersion: v1
kind: ConfigMap
metadata:
  name: goods-cm
  namespace: istio-demo
data:
  application-test.yml: |
    spring:
      datasource:
        driver-class-name: com.mysql.jdbc.Driver
        url: jdbc:mysql://192.168.3.230:3306/goods?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=GMT%2B8
        username: goods
        password: 365tskj.dev123456
      redis:
        host: 192.168.3.230
        database: 1
        port: 6379
        password: 365tskj.redis.12lguoyg4312b31p2
      cache:
        type: redis
---
#库存模块配置
apiVersion: v1
kind: ConfigMap
metadata:
  name: stock-cm
  namespace: istio-demo
data:
  application-test.yml: |
    spring:
      redis:
        host: 192.168.3.230
        database: 1
        port: 6379
        password: 365tskj.redis.12lguoyg4312b31p2
      cache:
        type: redis