#网络API
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: istio-demo-ingress
  namespace: istio-demo
spec:
  rules:
    - host: orderapp1.local.com
      http:
        paths:
          - path: /
            backend:
              serviceName: order
              servicePort: 8000
---
#网关
apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: istio-demo-gateway
  namespace: istio-demo
spec:
  selector:
    istio: ingressgateway
  servers:
    - port:
        number: 80
        name: http
        protocol: HTTP
      hosts:
        - "*"
---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: istio-demo-order-virual-service
  namespace: istio-demo
spec:
  hosts:
    - "*"
  gateways:
    - istio-demo-gateway
  http:
    - match:
        - uri:
            exact: /api/order/order/
      route:
        - destination:
            host: order
            port:
              number: 8000

---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: istio-demo-goods-virual-service
  namespace: istio-demo
spec:
  hosts:
    - "*"
  gateways:
    - istio-demo-gateway
  http:
    - match:
        - uri:
            exact: /api/goods/goods/
      route:
        - destination:
            host: goods
            port:
              number: 8001

---
##admin服务
#apiVersion: extensions/v1beta1
#kind: Ingress
#metadata:
#  name: istio-demo-admin-ingress
#  namespace: istio-demo
#spec:
#  rules:
#    - host: istio-demo-admin.test.com
#      http:
#        paths:
#          - path: /
#            backend:
#              serviceName: admin
#              servicePort: 7071