management:
  server:
    port: ${server.port}
  endpoints:
    beans:
      cache:
        time-to-live: 5s
    web:
      exposure:
        include: "*"
        exclude:
          - env
          - beans
      cors:
        allowed-origins: "*"
        allowed-methods: GET,POST,PUT,DELETE
    jmx:
      exposure:
        include: "*"
    prometheus:
      enabled: true
      metrics:
        - class-name: io.micrometer.core.instrument.binder.jvm.ClassLoaderMetrics
          enable: true
          explain: "类加载器"
        - class-name: io.micrometer.core.instrument.binder.jvm.JvmMemoryMetrics
          enable: true
          explain: "jvm内存监控"
        - class-name: io.micrometer.core.instrument.binder.jvm.JvmGcMetrics
          enable: true
          explain: "jvm gc回收监控"
        - class-name: io.micrometer.core.instrument.binder.jvm.JvmInfoMetrics
          enable: true
          explain: "jvm info监控"
        - class-name: io.micrometer.core.instrument.binder.jvm.JvmThreadMetrics
          enable: true
          explain: "jvm 线程监控"
    auditevents:
      enabled: true
    health:
      show-details: always
  metrics:
    tags:
      application: ${spring.application.name}
    export:
      prometheus:
        enabled: true
      simple:
        enabled: false
      jmx:
        enabled: true
  health:
    probes:
      enabled: true
    redis:
      enabled: true
    db:
      enabled: true
  info:
    git:
      enabled: true
      mode: full