management:
  server:
    port: ${server.port}
  endpoints:
    beans:
      cache:
        time-to-live: 5s
    web:
      exposure:
        include: "*"
        exclude:
          - env
          - beans
      cors:
        allowed-origins: "*"
        allowed-methods: GET,POST,PUT,DELETE
    jmx:
      exposure:
        include: "*"
    prometheus:
      enabled: true
      metrics:
        - class-name: io.micrometer.core.instrument.binder.jvm.ClassLoaderMetrics
          explain: "类加载器监控"
        - class-name: io.micrometer.core.instrument.binder.jvm.JvmCompilationMetrics
          explain: "jvm 编译策略监控"
        - class-name: io.micrometer.core.instrument.binder.jvm.JvmGcMetrics
          explain: "jvm gc回收监控"
        - class-name: io.micrometer.core.instrument.binder.jvm.JvmHeapPressureMetrics
          explain: "jvm 堆内存压力监控"
        - class-name: io.micrometer.core.instrument.binder.jvm.JvmInfoMetrics
          explain: "jvm info监控"
        - class-name: io.micrometer.core.instrument.binder.jvm.JvmMemoryMetrics
          explain: "jvm 内存监控"
        - class-name: io.micrometer.core.instrument.binder.jvm.JvmThreadMetrics
          explain: "jvm 线程监控"
        - class-name: io.github.mweirauch.micrometer.jvm.extras.ProcessMemoryMetrics
          explain: "系统内存监控"
        - class-name: io.github.mweirauch.micrometer.jvm.extras.ProcessThreadMetrics
          explain: "系统线程监控"
        - class-name: io.micrometer.core.instrument.binder.system.ProcessorMetrics
          explain: "系统进程监控"
        - class-name: io.micrometer.core.instrument.binder.system.UptimeMetrics
          explain: "系统进程创建时间监控"
    auditevents:
      enabled: true
    health:
      show-details: always
  metrics:
    tags:
      application: ${spring.application.name}
    export:
      prometheus:
        enabled: true
      simple:
        enabled: false
      jmx:
        enabled: true
  health:
    probes:
      enabled: true
    redis:
      enabled: true
    db:
      enabled: true
  info:
    git:
      enabled: true
      mode: full