spring:
  profiles:
    active: dev
  redis:
    host: 120.55.78.23
    database: 0
    port: 6379
    password: 365tskj.dev123456

management:
  endpoints:
    web:
      exposure:
        include: "*"
  health:
    probes:
      enabled: true

server:
  unavailable: ${random.int[5000,6000]}