spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://192.168.3.230:3306/goods?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=GMT%2B8
    username: goods
    password: 365tskj.dev123456
  redis:
    host: 192.168.3.230
    database: 0
    port: 6379
    password: 365tskj.redis.12lguoyg4312b31p2
  cache:
    type: redis